import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import ReduxProviders from "@/lib/ReduxProviders";
import { Toaster } from "sonner";

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProviders>
      <html lang="en">
        <body className={`${lexend.variable}`}>
          {children}
          <Toaster richColors expand={false} position="top-center" />
        </body>
      </html>
    </ReduxProviders>
  );
}
